# Generated by Django 4.1.7 on 2023-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_career_id_remove_profile_id_alter_career_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_profile',
            field=models.BooleanField(default=False),
        ),
    ]
